### ISSUE TITLE
add printing functionality

### ISSUE THREAD

**Issue by flicksolutions** [DHBern/2022_textgenerator-frontend_nb#12]
Output-Satz auf einem Thermodrucker drucken.

Noch offen:

- [x] Welches Druckermodell? @l0rn0r
- [x] Test-Gerät vorhanden? @l0rn0r
- [x] Umsetzung Prüfen. Via Node, Shell-Script ansteuern? @flicksolutions

[Command-Referenz](https://www.citizen-systems.com/resource/support/POS/Generic_Printer_Files/Command_Reference/CommandReference.pdf)

Propriettäres Tool um Binary-POS-Daten an Drucker zu schicken: [Send Data Tool](https://download.epson-biz.com/modules/pos/index.php?page=single_soft&cid=5027&scat=47&pcat=52)

**Comment by thodel** [comment]
Druckermodell:
Citizen CT-S310II
203 dpi, USB, Serial Port Buchse

Aktuell weiss niemand wo das Gerät ist. Dummerweise ist Viviane aktuell auch abwesend.
Gehe dem nach.

**Comment by flicksolutions** [comment]
@thodel 
Das Gerät ist bei mir Zuhause seit 15.07.! Das weiss auch Jonas.
Habe letzten Donnerstag das Ticket (fast) erledigt! Daher auch die drei Häkchen bei den Tasks!

Sorry, dass da wohl die Kommunikation nicht ganz klar war?
