### ISSUE TITLE
create sentence display

### ISSUE THREAD

**Issue by flicksolutions** [DHBern/2022_textgenerator-frontend_nb#3]
Erstellen der Display-Seite. Funktionale Komponenten:

- Text-Display
- Back to start Button
- Print-Funktion
- QR-Codes

**Comment by flicksolutions** [comment]
@l0rn0r im Moment bekomme ich immer nur einen einzigen Satz zurück. Ist etwas an meiner config falsch?
Das ist die aktuelle config:
```
{
		inputs: `Ich denke über ${$config.input},`,
		temperature: $config.temp,
		top_k: 50,
		max_length: 1000,
		num_return_sequences: 20,
		wait_for_model: false,
		use_cache: false
	}
```

**Comment by jnswidmer** [comment]
Auf oberster Ebene des Dicts hat man die Keys **inputs**, **parameters**, **options** (siehe [HuggingFace API Doku](https://huggingface.co/docs/api-inference/detailed_parameters#text-generation-task)).
Letztere beide sollen dann jeweils Dicts mit den entsprechenden Einträgen enthalten.
Hier:
```
{
        inputs: `Ich denke über ${$config.input},`,
        parameters: {
            temperature: $config.temp,
            top_k: 50,
            num_return_sequences: 20,
        },
        options: {
            wait_for_model: false,
            use_cache: false
       }
}
```
`max_length` gibt es nicht (und es wäre zu viel...).
Es gibt `max_new_tokens` mit der Range 0-250.

**Comment by flicksolutions** [comment]
Danke! Jetzt kommen da schon viel interessantere Antworten!
