### ISSUE TITLE
implement hennings endpoint

### ISSUE THREAD

**Issue by flicksolutions** [DHBern/2022_textgenerator-frontend_nb#7]
@l0rn0r Bitte gib mir bescheid, sobald es den hennings-endpoint gibt.

**Comment by jnswidmer** [comment]
@flicksolutions Von Hennings gibt es jetzt zwei Endpoints:
`dh-unibe/gpt2-ger-larger-hennings-maerchen` und
`dh-unibe/gpt2-ger-larger-hennings`
Aktuell zweiteres für das Frontend verwenden.

Hinweis: Nach dem ersten Training gab es unzählige Wortpaare, welche ohne Leerzeichen zwischen den Wörtern generiert wurden. Also habe ich den Datensatz angepasst und immer am Ende einer Satz-Zeile noch ein Leerschlag eingefügt - jetzt werden teilweise Blöcke an Leerzeichen generiert.
Diese also aktuell bitte rausfiltern (und evtl. Zeichenzahl beim Generator erhöhen), es gibt dann hoffentlich im August noch eine bessere Variante.

**Comment by flicksolutions** [comment]
Hennings wurde eingebunden und top_k auf 100 verdoppelt.
